### ISSUE TITLE
Backlight time

### ISSUE THREAD

**Issue by dpvue** [trekawek/aqi-lcd#13]
It looks that nothing happens when you change the Backlight Time in web config. It is always on.

**Comment by trekawek** [comment]
You're right. As far as I understand, this requires some hardware modifications, but for now it's confusing. I'll remove this option.

**Comment by trekawek** [comment]
It requires MOSFET transistor that can control the LCD backlight. See:
https://air.nettigo.pl/baza-wiedzy/wyswietlacz-z-wifi/?setlang=en
(unfortunately only in Polish)
