### ISSUE TITLE
AQI-LCD nie pobiera żadnych danych w sieci lokalnej, a z aqi.eco nie pobiera PM10

### ISSUE THREAD

**Issue by Krzysztof-z-Bagien** [trekawek/aqi-lcd#19]
Problem podobny (a właściwie to chyba dokładnie ten sam) do opisanego tutaj:
https://forum.kodujdlapolski.pl/t/zdalny-wyswietlacz-lcd-do-czujnika-smogu/3437/170
Zapewne jest to spowodowane tym, że nie używam domyślnego czujnika pyłów (SDS011), tylko SPS30, który generuje dużo więcej danych, więc i dłuższy plik .json.

Ten sam problem występuje też w przypadku AQI-LED (lokalnie nie pobiera danych, świeci tylko pierwsza dioda - na zielono).

**Comment by trekawek** [comment]
@Krzysztof-z-Bagien, możesz podesłać przykładowy plik JSON zwracany przez Twój czujnik?

**Comment by Krzysztof-z-Bagien** [comment]
Plik z aqi.eco:
https://nowosolna.aqi.eco/pl/topolowa/data.json

Plik z czujnika:
[data.zip](https://github.com/trekawek/aqi-lcd/files/7668920/data.zip)

**Comment by trekawek** [comment]
W 9c2648938ebde9c978bf72729b91655fab6dd6e9 powiększyłem ilość dostępnej pamięci zgodnie z zaleceniami
https://arduinojson.org/v6/assistant/

Nowe binarki są dostępne tu:
https://github.com/trekawek/aqi-lcd/tree/master/bin

**Comment by Krzysztof-z-Bagien** [comment]
Teraz z aqi.eco pobiera i wyświetla dane jak trzeba; lokalnie wyświetla się temperatura i ciśnienie (wcześniej były same zera), ale pyłów nadal nie pokazuje.

Zgaduję, że nie podoba mu się to "value_type":"SPS30_P2" itp., bo spodziewa się czegoś z SDS11.

**Comment by trekawek** [comment]
Może 1a32f09e91f896e3a21755cf69cac99c5d4fccda pomoże. Spróbuj proszę z nowymi binarkami, adres jak poprzednio.

**Comment by Krzysztof-z-Bagien** [comment]
Wygląda na to, że jest git, zarówno LED jak i LCD poprawnie pobierają dane w sieci lokalnej - dziękuję :)
