### ISSUE TITLE
Credentials needed after initial wifi setup

### ISSUE THREAD

**Issue by andygodber** [trekawek/aqi-lcd#20]
Ive managed to connect the LCD to my wifi network and it gets an IP address.
When I go to the web page for config, Im asked for credentials - what are they?
(Ive tried the SSID etc!)

**Comment by trekawek** [comment]
Hi Andy,

I think the username should be `admin` and the password is the one that you've set as AP password in the configuration page.

Please let me know if it works.

**Comment by andygodber** [comment]
Hi Tomek – that worked perfectly thanks.

Now Ive got to work out why Im not seeing anything on the display other than the signal strength and time icons 😉

Andy

**Comment by andygodber** [comment]
Now confirmed fully working, including display - local address needs HTTP:// in front.
