### ISSUE TITLE
Lokalna temperatura

### ISSUE THREAD

**Issue by prezeskk** [trekawek/aqi-lcd#3]
Czy jest możliwość podpięcia lokalnego czujnika np BME280? I odczyt wartości w miejscu czujnika (oprócz danych z czujnika luftdaten)

**Comment by trekawek** [comment]
Nie próbowałem, ale @irukard wspomniał możliwości podpinania urządzeń obsługujących SPI:
https://forum.kodujdlapolski.pl/t/zdalny-wyswietlacz-lcd-do-czujnika-smogu/3437/60w
Więc pewnie się da.

A co do odczytu w samym firmware - pewnie, że możliwość istnieje, tylko trzeba to oprogramować :)

**Comment by prezeskk** [comment]
https://github.com/trekawek/aqi-lcd/pull/10

**Comment by trekawek** [comment]
Closing in favour of #10.
